backend:
  name: github
  repo: SAMT-BU/team-architecture
  branch: main
  base_url: https://samt-bu-cms-auth.erik-hag1.workers.dev

local_backend: true

media_folder: static/images
public_folder: /images

i18n:
  structure: multiple_files
  locales: [en]
  default_locale: en

collections:
  - name: arkitektur
    label: "Team architecture"
    label_singular: "Page"
    folder: content
    nested:
      depth: 10
      summary: "{{title}}"
    path: "{{dir}}/_index"
    create: true
    i18n: true
    media_folder: ""
    public_folder: ""
    sortable_fields: ['weight', 'title']
    fields:
      - label: "Unique ID"
        name: id
        widget: hidden
        i18n: duplicate

      - label: Title
        name: title
        widget: string
        i18n: true

      - label: Navigation title
        name: linkTitle
        widget: string
        i18n: true
        required: false

      - label: Sort order
        name: weight
        widget: number
        value_type: int
        i18n: duplicate
        required: false

      - label: Status
        name: status
        widget: select
        options:
          - { label: "◍ New", value: "New" }
          - { label: "◔ Early draft", value: "Early draft" }
          - { label: "◐ In progress", value: "In progress" }
          - { label: "◕ For QA", value: "For QA" }
          - { label: "⏺ Approved", value: "Approved" }
          - { label: "⨂ Cancelled", value: "Cancelled" }
        required: false
        i18n: true
        hint: "The symbol is generated automatically by the website"

      - label: Content
        name: body
        widget: markdown
        i18n: true
        required: false
