baseURL = "https://samt-bu.github.io/samt-bu-docs/"
title = "SAMT-BU Dokumentasjon"
theme = "hugo-theme-samt-bu"
defaultContentLanguage = "nb"
defaultContentLanguageInSubdir = false
enableGitInfo = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.nb]
    languageCode = "nb-NO"
    languageName = "Bokmål"
    title = "SAMT-BU Dokumentasjon"
    weight = 1
    [languages.nb.params]
      navSwitcherLabel = "Innhold"
      navSwitcherPlaceholder = "Velg seksjon"
  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    title = "SAMT-BU Documentation"
    weight = 2
    [languages.en.params]
      navSwitcherLabel = "Content"
      navSwitcherPlaceholder = "Select section"

[markup.goldmark.renderer]
  unsafe = true

[params]
  editURL = "https://github.com/SAMT-BU/samt-bu-docs/edit/main/content/"

[[params.navSwitcher]]
  id = "om"
  title = "Om"
  url = "om/"
  icon = "fa-info-circle"

[[params.navSwitcher]]
  id = "behov"
  title = "Behov"
  url = "behov/"
  icon = "fa-lightbulb-o"

[[params.navSwitcher]]
  id = "pilotering"
  title = "Piloter"
  url = "pilotering/"
  icon = "fa-flask"

[[params.navSwitcher]]
  id = "arkitektur"
  title = "Arkitektur"
  url = "arkitektur/"
  icon = "fa-sitemap"

[[params.navSwitcher]]
  id = "loesning"
  title = "Løsninger"
  url = "loesning/"
  icon = "fa-cogs"

[[params.navSwitcher]]
  id = "rammeverk"
  title = "Rammeverk"
  url = "rammeverk/"
  icon = "fa-cubes"

[[params.navSwitcher]]
  id = "informasjonsmodeller"
  title = "Informasjonsmodeller"
  url = "informasjonsmodeller/"
  icon = "fa-database"

[[params.navSwitcher]]
  id = "innsikt"
  title = "Felles innsikt"
  url = "innsikt/"
  icon = "fa-bar-chart"
