baseURL = "https://samt-bu.github.io/samt-bu-docs/"
title = "SAMT-BU Dokumentasjon"
theme = "hugo-theme-samt-bu"
defaultContentLanguage = "nb"
defaultContentLanguageInSubdir = false
enableGitInfo = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.nb]
    languageCode = "nb-NO"
    languageName = "Bokmål"
    title = "SAMT-BU Dokumentasjon"
    weight = 1
  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    title = "SAMT-BU Documentation"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true

[params]
  editURL = "https://github.com/SAMT-BU/samt-bu-docs/edit/main/content/"
  navSwitcherLabel = "Tema"
  navSwitcherPlaceholder = "Velg tema"

[[params.navSwitcher]]
  id = "behov"
  title = "Behov"
  url = "temaer/behov/"
  icon = "fa-lightbulb-o"

[[params.navSwitcher]]
  id = "pilotering"
  title = "Piloter"
  url = "temaer/pilotering/"
  icon = "fa-flask"

[[params.navSwitcher]]
  id = "arkitektur"
  title = "Arkitektur"
  url = "temaer/arkitektur/"
  icon = "fa-sitemap"

[[params.navSwitcher]]
  id = "loesning"
  title = "Løsninger"
  url = "temaer/loesning/"
  icon = "fa-cogs"

[[params.navSwitcher]]
  id = "rammeverk"
  title = "Rammeverk"
  url = "temaer/rammeverk/"
  icon = "fa-cubes"

[[params.navSwitcher]]
  id = "informasjonsmodeller"
  title = "Informasjonsmodeller"
  url = "temaer/informasjonsmodeller/"
  icon = "fa-database"

[module]
  [[module.imports]]
    path = "github.com/SAMT-BU/samt-bu-innspill"
    [[module.imports.mounts]]
      source = "content"
      target = "content/innspill"

  [[module.imports]]
    path = "github.com/SAMT-BU/samt-bu-org-digdir"
    [[module.imports.mounts]]
      source = "content"
      target = "content/innspill/prosjektpartnere/digdir"

  [[module.imports]]
    path = "github.com/SAMT-BU/samt-bu-org-ks"
    [[module.imports.mounts]]
      source = "content"
      target = "content/innspill/prosjektpartnere/ks"

  [[module.imports]]
    path = "github.com/SAMT-BU/samt-bu-org-ks-digital"
    [[module.imports.mounts]]
      source = "content"
      target = "content/innspill/prosjektpartnere/ks-digital"

  [[module.imports]]
    path = "github.com/SAMT-BU/samt-bu-org-hk-dir"
    [[module.imports.mounts]]
      source = "content"
      target = "content/innspill/prosjektpartnere/hk-dir"

  [[module.imports]]
    path = "github.com/SAMT-BU/samt-bu-org-udir"
    [[module.imports.mounts]]
      source = "content"
      target = "content/innspill/prosjektpartnere/udir"

  [[module.imports]]
    path = "github.com/SAMT-BU/samt-bu-org-sikt"
    [[module.imports.mounts]]
      source = "content"
      target = "content/innspill/prosjektpartnere/sikt"

  [[module.imports]]
    path = "github.com/SAMT-BU/samt-bu-org-staf"
    [[module.imports.mounts]]
      source = "content"
      target = "content/innspill/prosjektpartnere/staf"

  [[module.imports]]
    path = "github.com/SAMT-BU/samt-bu-org-ssb"
    [[module.imports.mounts]]
      source = "content"
      target = "content/innspill/prosjektpartnere/ssb"

  [[module.imports]]
    path = "github.com/SAMT-BU/samt-bu-org-novari"
    [[module.imports.mounts]]
      source = "content"
      target = "content/innspill/prosjektpartnere/novari"

  [[module.imports]]
    path = "github.com/SAMT-BU/samt-bu-org-andre"
    [[module.imports.mounts]]
      source = "content"
      target = "content/innspill/andre"

  [[module.imports]]
    path = "github.com/SAMT-BU/samt-bu-innsikt"
    [[module.imports.mounts]]
      source = "content"
      target = "content/innsikt"

  [[module.imports]]
    path = "github.com/SAMT-BU/samt-bu-arkitektur"
    [[module.imports.mounts]]
      source = "content"
      target = "content/temaer/arkitektur"
