baseURL = "https://samt-bu.github.io/samt-bu-docs/"
title = "SAMT-BU Dokumentasjon"
languageCode = "nb"

[module]
  [[module.imports]]
    path = "github.com/altinn/hugo-theme-altinn"

[params]
  # tilpasses senere