baseURL = "https://samt-bu.github.io/samt-bu-docs/"
title = "SAMT-BU Dokumentasjon"
theme = "hugo-theme-altinn"
defaultContentLanguage = "nb"
defaultContentLanguageInSubdir = false
enableGitInfo = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[languages]
  [languages.nb]
    languageCode = "nb-NO"
    languageName = "Bokm√•l"
    title = "SAMT-BU Dokumentasjon"
    weight = 1
  [languages.en]
    languageCode = "en-US"
    languageName = "English"
    title = "SAMT-BU Documentation"
    weight = 2

[params]
  editURL = "https://github.com/SAMT-BU/samt-bu-docs/edit/main/content/"
