backend:
  name: github
  repo: SAMT-BU/samt-bu-drafts
  branch: main
  base_url: https://samt-bu-cms-auth.erik-hag1.workers.dev

local_backend: true

locale: nb

media_folder: static/images
public_folder: /images

i18n:
  structure: multiple_files
  locales: [nb]
  default_locale: nb

collections:
  - name: utkast
    label: "Innspill og utkast"
    label_singular: "Side"
    folder: content
    nested:
      depth: 10
      summary: "{{title}}"
    path: "{{dir}}/_index"
    create: true
    i18n: true
    media_folder: ""
    public_folder: ""
    sortable_fields: ['weight', 'title']
    fields:
      - label: "Unik ID"
        name: id
        widget: uuid
        i18n: duplicate
        required: false
        hint: "Auto-generert identifikator – skal aldri endres"

      - label: Tittel
        name: title
        widget: string
        i18n: true

      - label: Navigasjonstittel
        name: linkTitle
        widget: string
        i18n: true
        required: false

      - label: Sorteringsrekkefølge
        name: weight
        widget: number
        value_type: int
        i18n: duplicate
        required: false

      - label: Innholdsfortegnelse
        name: toc
        widget: boolean
        default: true
        i18n: duplicate
        required: false

      - label: Status
        name: status
        widget: select
        options:
          - { label: "◍ Ny", value: "Ny" }
          - { label: "◔ Tidlig utkast", value: "Tidlig utkast" }
          - { label: "◐ Pågår", value: "Pågår" }
          - { label: "◕ Til QA", value: "Til QA" }
          - { label: "⏺ Godkjent", value: "Godkjent" }
          - { label: "⨂ Avbrutt", value: "Avbrutt" }
        required: false
        i18n: duplicate
        hint: "Symbolet genereres automatisk av nettstedet – ikke legg det til i linkTitle"

      - label: Innhold
        name: body
        widget: markdown
        i18n: true
